### PR TITLE
[WIP] script to lock issues

### PR DESCRIPTION
**Pull request by ohwutup**
there is some cruft left over from the script we copied from, ill clean that up

### CODE REVIEW

**Comment by KrauseFx** [comment]
Looks great, did you try it already?

**Comment by ohwutup** [comment]
Yup! Just finished running it on all the things! :tada:

**Comment by KrauseFx** [comment]
Let's :rocket: it

**Comment by KrauseFx** [comment]
I'll close this PR for now, since it's not something we plan on doing any more, right? It hasn't been a problem.

**Pull request closed without merging**
